### ISSUE TITLE
Obecny etap pracy

### ISSUE THREAD

**Issue by olimari** [olimari/IO_2019_2020_PLATFORMOWKA#13]
![image](https://user-images.githubusercontent.com/62391424/82649689-e64ad200-9c19-11ea-83d1-994bd68dea7b.png)
Postać porusza się, skacze, zbiera pieniądze(które naliczają się do wyniku), zbiera klucz, otwiera portal, jeśli spada przegrywa/jeśli wygrywa portal się zmienia(otwiera) - występuję odpowiedni komunikat do sytuacji.

Niedopracowana jest jeszcze przezroczystość gifów,ale to już będzie robił Szymon.

**Comment by feellikenjel** [comment]
Ze strony graficznej: przygotowane grafiki jeśli chodzi o gameplay włącznie z animacjami grafik znaczących. Do przygotowania pozostało UI: menu główne, ewentualne menu pauzy oraz komunikat o wygranej/przegranej.
Dobrana również została biblioteka audio poza muzyką w backgroundzie i w menu.
